#!/usr/bin/env node
/*
 * MangaShelf frontend build.
 *
 * The app's .jsx files were written to run as separate <script type="text/babel">
 * tags compiled in the browser. They share GLOBAL scope (no import/export) and
 * communicate through `window.*` and the global `React` — several files even
 * declare the same top-level names (e.g. `const { useState } = React` in both
 * components.jsx and app.jsx), which only works because each <script> has its own
 * scope.
 *
 * To preserve that exactly while shipping ONE precompiled, minified file, we:
 *   1. transform each .jsx from JSX -> JS with esbuild (no bundling),
 *   2. wrap each file in its own IIFE so top-level names stay file-scoped
 *      (identical isolation to the separate <script> tags), and
 *   3. concatenate them in load order into static/app.bundle.js.
 *
 * api.js is plain JS loaded before the app; it stays a separate <script> (it sets
 * up window.ApiClient etc. that the bundle reads at runtime), so it is NOT bundled
 * here — no need, and keeping it separate matches the original load order.
 *
 * Run:  node web/build.js         (one-off)
 *       node web/build.js --watch (rebuild on change)
 */
const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const STATIC = path.join(__dirname, "static");
const OUT = path.join(STATIC, "app.bundle.js");

// Load order MUST match the original index.html script order.
const FILES = [
  "tweaks-shim.jsx",
  "components.jsx",
  "screens-library.jsx",
  "screens-reader.jsx",
  "screens-detail.jsx",
  "app.jsx",
];

async function buildOnce() {
  const parts = [];
  for (const name of FILES) {
    const src = fs.readFileSync(path.join(STATIC, name), "utf8");
    const { code } = await esbuild.transform(src, {
      loader: "jsx",
      jsx: "transform",           // classic runtime — uses the global React
      minify: true,
      // Keep it targeting broadly-supported syntax for phone browsers.
      target: ["es2018"],
    });
    // Wrap each file so its top-level declarations stay isolated, mirroring the
    // per-<script> scoping the source was written for.
    parts.push(`/* ${name} */\n(function(){\n${code}\n})();`);
  }
  const banner = "/* MangaShelf bundle — generated by build.js. Do not edit; edit the .jsx sources. */\n";
  fs.writeFileSync(OUT, banner + parts.join("\n"), "utf8");
  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`built static/app.bundle.js (${kb} KB) from ${FILES.length} sources`);
}

async function main() {
  await buildOnce();
  if (process.argv.includes("--watch")) {
    console.log("watching for changes… (Ctrl+C to stop)");
    let timer = null;
    for (const name of FILES) {
      fs.watch(path.join(STATIC, name), () => {
        clearTimeout(timer);
        timer = setTimeout(() => buildOnce().catch((e) => console.error(e)), 120);
      });
    }
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
